#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizSystem
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuizSystem")]
	public partial class QuizSystemDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCauHoi(CauHoi instance);
    partial void UpdateCauHoi(CauHoi instance);
    partial void DeleteCauHoi(CauHoi instance);
    partial void InsertPhongThi(PhongThi instance);
    partial void UpdatePhongThi(PhongThi instance);
    partial void DeletePhongThi(PhongThi instance);
    partial void InsertChiTietDeThi(ChiTietDeThi instance);
    partial void UpdateChiTietDeThi(ChiTietDeThi instance);
    partial void DeleteChiTietDeThi(ChiTietDeThi instance);
    partial void InsertDanhSachGiamThi(DanhSachGiamThi instance);
    partial void UpdateDanhSachGiamThi(DanhSachGiamThi instance);
    partial void DeleteDanhSachGiamThi(DanhSachGiamThi instance);
    partial void InsertDanhSachSinhVienThi(DanhSachSinhVienThi instance);
    partial void UpdateDanhSachSinhVienThi(DanhSachSinhVienThi instance);
    partial void DeleteDanhSachSinhVienThi(DanhSachSinhVienThi instance);
    partial void InsertDanhSachThi(DanhSachThi instance);
    partial void UpdateDanhSachThi(DanhSachThi instance);
    partial void DeleteDanhSachThi(DanhSachThi instance);
    partial void InsertDeThi(DeThi instance);
    partial void UpdateDeThi(DeThi instance);
    partial void DeleteDeThi(DeThi instance);
    partial void InsertGiangVien(GiangVien instance);
    partial void UpdateGiangVien(GiangVien instance);
    partial void DeleteGiangVien(GiangVien instance);
    partial void InsertHocPhan(HocPhan instance);
    partial void UpdateHocPhan(HocPhan instance);
    partial void DeleteHocPhan(HocPhan instance);
    partial void InsertKetQuaThi(KetQuaThi instance);
    partial void UpdateKetQuaThi(KetQuaThi instance);
    partial void DeleteKetQuaThi(KetQuaThi instance);
    partial void InsertKhoa(Khoa instance);
    partial void UpdateKhoa(Khoa instance);
    partial void DeleteKhoa(Khoa instance);
    partial void InsertSinhVien(SinhVien instance);
    partial void UpdateSinhVien(SinhVien instance);
    partial void DeleteSinhVien(SinhVien instance);
    #endregion
		
		public QuizSystemDataContext() : 
				base(global::QuizSystem.Properties.Settings.Default.QuizSystemConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public QuizSystemDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuizSystemDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuizSystemDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuizSystemDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CauHoi> CauHois
		{
			get
			{
				return this.GetTable<CauHoi>();
			}
		}
		
		public System.Data.Linq.Table<PhongThi> PhongThis
		{
			get
			{
				return this.GetTable<PhongThi>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietDeThi> ChiTietDeThis
		{
			get
			{
				return this.GetTable<ChiTietDeThi>();
			}
		}
		
		public System.Data.Linq.Table<DanhSachGiamThi> DanhSachGiamThis
		{
			get
			{
				return this.GetTable<DanhSachGiamThi>();
			}
		}
		
		public System.Data.Linq.Table<DanhSachSinhVienThi> DanhSachSinhVienThis
		{
			get
			{
				return this.GetTable<DanhSachSinhVienThi>();
			}
		}
		
		public System.Data.Linq.Table<DanhSachThi> DanhSachThis
		{
			get
			{
				return this.GetTable<DanhSachThi>();
			}
		}
		
		public System.Data.Linq.Table<DeThi> DeThis
		{
			get
			{
				return this.GetTable<DeThi>();
			}
		}
		
		public System.Data.Linq.Table<GiangVien> GiangViens
		{
			get
			{
				return this.GetTable<GiangVien>();
			}
		}
		
		public System.Data.Linq.Table<HocPhan> HocPhans
		{
			get
			{
				return this.GetTable<HocPhan>();
			}
		}
		
		public System.Data.Linq.Table<KetQuaThi> KetQuaThis
		{
			get
			{
				return this.GetTable<KetQuaThi>();
			}
		}
		
		public System.Data.Linq.Table<Khoa> Khoas
		{
			get
			{
				return this.GetTable<Khoa>();
			}
		}
		
		public System.Data.Linq.Table<SinhVien> SinhViens
		{
			get
			{
				return this.GetTable<SinhVien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CauHoi")]
	public partial class CauHoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaSoCH;
		
		private string _NoiDung;
		
		private string _PhuongAnA;
		
		private string _PhuongAnB;
		
		private string _PhuongAnC;
		
		private string _PhuongAnD;
		
		private System.Nullable<char> _DapAnDung;
		
		private string _DoKho;
		
		private string _MaSoHP;
		
		private string _GiangVienSoan;
		
		private EntitySet<ChiTietDeThi> _ChiTietDeThis;
		
		private EntityRef<GiangVien> _GiangVien;
		
		private EntityRef<HocPhan> _HocPhan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSoCHChanging(int value);
    partial void OnMaSoCHChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnPhuongAnAChanging(string value);
    partial void OnPhuongAnAChanged();
    partial void OnPhuongAnBChanging(string value);
    partial void OnPhuongAnBChanged();
    partial void OnPhuongAnCChanging(string value);
    partial void OnPhuongAnCChanged();
    partial void OnPhuongAnDChanging(string value);
    partial void OnPhuongAnDChanged();
    partial void OnDapAnDungChanging(System.Nullable<char> value);
    partial void OnDapAnDungChanged();
    partial void OnDoKhoChanging(string value);
    partial void OnDoKhoChanged();
    partial void OnMaSoHPChanging(string value);
    partial void OnMaSoHPChanged();
    partial void OnGiangVienSoanChanging(string value);
    partial void OnGiangVienSoanChanged();
    #endregion
		
		public CauHoi()
		{
			this._ChiTietDeThis = new EntitySet<ChiTietDeThi>(new Action<ChiTietDeThi>(this.attach_ChiTietDeThis), new Action<ChiTietDeThi>(this.detach_ChiTietDeThis));
			this._GiangVien = default(EntityRef<GiangVien>);
			this._HocPhan = default(EntityRef<HocPhan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSoCH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaSoCH
		{
			get
			{
				return this._MaSoCH;
			}
			set
			{
				if ((this._MaSoCH != value))
				{
					this.OnMaSoCHChanging(value);
					this.SendPropertyChanging();
					this._MaSoCH = value;
					this.SendPropertyChanged("MaSoCH");
					this.OnMaSoCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(200)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuongAnA", DbType="NVarChar(120)")]
		public string PhuongAnA
		{
			get
			{
				return this._PhuongAnA;
			}
			set
			{
				if ((this._PhuongAnA != value))
				{
					this.OnPhuongAnAChanging(value);
					this.SendPropertyChanging();
					this._PhuongAnA = value;
					this.SendPropertyChanged("PhuongAnA");
					this.OnPhuongAnAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuongAnB", DbType="NVarChar(120)")]
		public string PhuongAnB
		{
			get
			{
				return this._PhuongAnB;
			}
			set
			{
				if ((this._PhuongAnB != value))
				{
					this.OnPhuongAnBChanging(value);
					this.SendPropertyChanging();
					this._PhuongAnB = value;
					this.SendPropertyChanged("PhuongAnB");
					this.OnPhuongAnBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuongAnC", DbType="NVarChar(120)")]
		public string PhuongAnC
		{
			get
			{
				return this._PhuongAnC;
			}
			set
			{
				if ((this._PhuongAnC != value))
				{
					this.OnPhuongAnCChanging(value);
					this.SendPropertyChanging();
					this._PhuongAnC = value;
					this.SendPropertyChanged("PhuongAnC");
					this.OnPhuongAnCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuongAnD", DbType="NVarChar(120)")]
		public string PhuongAnD
		{
			get
			{
				return this._PhuongAnD;
			}
			set
			{
				if ((this._PhuongAnD != value))
				{
					this.OnPhuongAnDChanging(value);
					this.SendPropertyChanging();
					this._PhuongAnD = value;
					this.SendPropertyChanged("PhuongAnD");
					this.OnPhuongAnDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DapAnDung", DbType="Char(1)")]
		public System.Nullable<char> DapAnDung
		{
			get
			{
				return this._DapAnDung;
			}
			set
			{
				if ((this._DapAnDung != value))
				{
					this.OnDapAnDungChanging(value);
					this.SendPropertyChanging();
					this._DapAnDung = value;
					this.SendPropertyChanged("DapAnDung");
					this.OnDapAnDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoKho", DbType="NVarChar(60)")]
		public string DoKho
		{
			get
			{
				return this._DoKho;
			}
			set
			{
				if ((this._DoKho != value))
				{
					this.OnDoKhoChanging(value);
					this.SendPropertyChanging();
					this._DoKho = value;
					this.SendPropertyChanged("DoKho");
					this.OnDoKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSoHP", DbType="VarChar(5)")]
		public string MaSoHP
		{
			get
			{
				return this._MaSoHP;
			}
			set
			{
				if ((this._MaSoHP != value))
				{
					if (this._HocPhan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSoHPChanging(value);
					this.SendPropertyChanging();
					this._MaSoHP = value;
					this.SendPropertyChanged("MaSoHP");
					this.OnMaSoHPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiangVienSoan", DbType="VarChar(5)")]
		public string GiangVienSoan
		{
			get
			{
				return this._GiangVienSoan;
			}
			set
			{
				if ((this._GiangVienSoan != value))
				{
					if (this._GiangVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGiangVienSoanChanging(value);
					this.SendPropertyChanging();
					this._GiangVienSoan = value;
					this.SendPropertyChanged("GiangVienSoan");
					this.OnGiangVienSoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_ChiTietDeThi", Storage="_ChiTietDeThis", ThisKey="MaSoCH", OtherKey="MaSoCH")]
		public EntitySet<ChiTietDeThi> ChiTietDeThis
		{
			get
			{
				return this._ChiTietDeThis;
			}
			set
			{
				this._ChiTietDeThis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_CauHoi", Storage="_GiangVien", ThisKey="GiangVienSoan", OtherKey="MaSoGV", IsForeignKey=true)]
		public GiangVien GiangVien
		{
			get
			{
				return this._GiangVien.Entity;
			}
			set
			{
				GiangVien previousValue = this._GiangVien.Entity;
				if (((previousValue != value) 
							|| (this._GiangVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiangVien.Entity = null;
						previousValue.CauHois.Remove(this);
					}
					this._GiangVien.Entity = value;
					if ((value != null))
					{
						value.CauHois.Add(this);
						this._GiangVienSoan = value.MaSoGV;
					}
					else
					{
						this._GiangVienSoan = default(string);
					}
					this.SendPropertyChanged("GiangVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocPhan_CauHoi", Storage="_HocPhan", ThisKey="MaSoHP", OtherKey="MaSoHP", IsForeignKey=true)]
		public HocPhan HocPhan
		{
			get
			{
				return this._HocPhan.Entity;
			}
			set
			{
				HocPhan previousValue = this._HocPhan.Entity;
				if (((previousValue != value) 
							|| (this._HocPhan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HocPhan.Entity = null;
						previousValue.CauHois.Remove(this);
					}
					this._HocPhan.Entity = value;
					if ((value != null))
					{
						value.CauHois.Add(this);
						this._MaSoHP = value.MaSoHP;
					}
					else
					{
						this._MaSoHP = default(string);
					}
					this.SendPropertyChanged("HocPhan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietDeThis(ChiTietDeThi entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi = this;
		}
		
		private void detach_ChiTietDeThis(ChiTietDeThi entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhongThi")]
	public partial class PhongThi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhongThi;
		
		private string _TenPhong;
		
		private EntitySet<DanhSachThi> _DanhSachThis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhongThiChanging(string value);
    partial void OnMaPhongThiChanged();
    partial void OnTenPhongChanging(string value);
    partial void OnTenPhongChanged();
    #endregion
		
		public PhongThi()
		{
			this._DanhSachThis = new EntitySet<DanhSachThi>(new Action<DanhSachThi>(this.attach_DanhSachThis), new Action<DanhSachThi>(this.detach_DanhSachThis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhongThi", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhongThi
		{
			get
			{
				return this._MaPhongThi;
			}
			set
			{
				if ((this._MaPhongThi != value))
				{
					this.OnMaPhongThiChanging(value);
					this.SendPropertyChanging();
					this._MaPhongThi = value;
					this.SendPropertyChanged("MaPhongThi");
					this.OnMaPhongThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhong", DbType="NVarChar(20)")]
		public string TenPhong
		{
			get
			{
				return this._TenPhong;
			}
			set
			{
				if ((this._TenPhong != value))
				{
					this.OnTenPhongChanging(value);
					this.SendPropertyChanging();
					this._TenPhong = value;
					this.SendPropertyChanged("TenPhong");
					this.OnTenPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongThi_DanhSachThi", Storage="_DanhSachThis", ThisKey="MaPhongThi", OtherKey="MaPhongThi")]
		public EntitySet<DanhSachThi> DanhSachThis
		{
			get
			{
				return this._DanhSachThis;
			}
			set
			{
				this._DanhSachThis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DanhSachThis(DanhSachThi entity)
		{
			this.SendPropertyChanging();
			entity.PhongThi = this;
		}
		
		private void detach_DanhSachThis(DanhSachThi entity)
		{
			this.SendPropertyChanging();
			entity.PhongThi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietDeThi")]
	public partial class ChiTietDeThi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDeThi;
		
		private int _MaSoCH;
		
		private EntityRef<CauHoi> _CauHoi;
		
		private EntityRef<DeThi> _DeThi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDeThiChanging(int value);
    partial void OnMaDeThiChanged();
    partial void OnMaSoCHChanging(int value);
    partial void OnMaSoCHChanged();
    #endregion
		
		public ChiTietDeThi()
		{
			this._CauHoi = default(EntityRef<CauHoi>);
			this._DeThi = default(EntityRef<DeThi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDeThi", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaDeThi
		{
			get
			{
				return this._MaDeThi;
			}
			set
			{
				if ((this._MaDeThi != value))
				{
					if (this._DeThi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDeThiChanging(value);
					this.SendPropertyChanging();
					this._MaDeThi = value;
					this.SendPropertyChanged("MaDeThi");
					this.OnMaDeThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSoCH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaSoCH
		{
			get
			{
				return this._MaSoCH;
			}
			set
			{
				if ((this._MaSoCH != value))
				{
					if (this._CauHoi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSoCHChanging(value);
					this.SendPropertyChanging();
					this._MaSoCH = value;
					this.SendPropertyChanged("MaSoCH");
					this.OnMaSoCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_ChiTietDeThi", Storage="_CauHoi", ThisKey="MaSoCH", OtherKey="MaSoCH", IsForeignKey=true)]
		public CauHoi CauHoi
		{
			get
			{
				return this._CauHoi.Entity;
			}
			set
			{
				CauHoi previousValue = this._CauHoi.Entity;
				if (((previousValue != value) 
							|| (this._CauHoi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CauHoi.Entity = null;
						previousValue.ChiTietDeThis.Remove(this);
					}
					this._CauHoi.Entity = value;
					if ((value != null))
					{
						value.ChiTietDeThis.Add(this);
						this._MaSoCH = value.MaSoCH;
					}
					else
					{
						this._MaSoCH = default(int);
					}
					this.SendPropertyChanged("CauHoi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DeThi_ChiTietDeThi", Storage="_DeThi", ThisKey="MaDeThi", OtherKey="MaDeThi", IsForeignKey=true)]
		public DeThi DeThi
		{
			get
			{
				return this._DeThi.Entity;
			}
			set
			{
				DeThi previousValue = this._DeThi.Entity;
				if (((previousValue != value) 
							|| (this._DeThi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DeThi.Entity = null;
						previousValue.ChiTietDeThis.Remove(this);
					}
					this._DeThi.Entity = value;
					if ((value != null))
					{
						value.ChiTietDeThis.Add(this);
						this._MaDeThi = value.MaDeThi;
					}
					else
					{
						this._MaDeThi = default(int);
					}
					this.SendPropertyChanged("DeThi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhSachGiamThi")]
	public partial class DanhSachGiamThi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDS;
		
		private string _MaSoGiamThi;
		
		private EntityRef<DanhSachThi> _DanhSachThi;
		
		private EntityRef<GiangVien> _GiangVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDSChanging(string value);
    partial void OnMaDSChanged();
    partial void OnMaSoGiamThiChanging(string value);
    partial void OnMaSoGiamThiChanged();
    #endregion
		
		public DanhSachGiamThi()
		{
			this._DanhSachThi = default(EntityRef<DanhSachThi>);
			this._GiangVien = default(EntityRef<GiangVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDS", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDS
		{
			get
			{
				return this._MaDS;
			}
			set
			{
				if ((this._MaDS != value))
				{
					if (this._DanhSachThi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDSChanging(value);
					this.SendPropertyChanging();
					this._MaDS = value;
					this.SendPropertyChanged("MaDS");
					this.OnMaDSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSoGiamThi", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSoGiamThi
		{
			get
			{
				return this._MaSoGiamThi;
			}
			set
			{
				if ((this._MaSoGiamThi != value))
				{
					if (this._GiangVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSoGiamThiChanging(value);
					this.SendPropertyChanging();
					this._MaSoGiamThi = value;
					this.SendPropertyChanged("MaSoGiamThi");
					this.OnMaSoGiamThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DanhSachThi_DanhSachGiamThi", Storage="_DanhSachThi", ThisKey="MaDS", OtherKey="MaDS", IsForeignKey=true)]
		public DanhSachThi DanhSachThi
		{
			get
			{
				return this._DanhSachThi.Entity;
			}
			set
			{
				DanhSachThi previousValue = this._DanhSachThi.Entity;
				if (((previousValue != value) 
							|| (this._DanhSachThi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DanhSachThi.Entity = null;
						previousValue.DanhSachGiamThis.Remove(this);
					}
					this._DanhSachThi.Entity = value;
					if ((value != null))
					{
						value.DanhSachGiamThis.Add(this);
						this._MaDS = value.MaDS;
					}
					else
					{
						this._MaDS = default(string);
					}
					this.SendPropertyChanged("DanhSachThi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_DanhSachGiamThi", Storage="_GiangVien", ThisKey="MaSoGiamThi", OtherKey="MaSoGV", IsForeignKey=true)]
		public GiangVien GiangVien
		{
			get
			{
				return this._GiangVien.Entity;
			}
			set
			{
				GiangVien previousValue = this._GiangVien.Entity;
				if (((previousValue != value) 
							|| (this._GiangVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiangVien.Entity = null;
						previousValue.DanhSachGiamThis.Remove(this);
					}
					this._GiangVien.Entity = value;
					if ((value != null))
					{
						value.DanhSachGiamThis.Add(this);
						this._MaSoGiamThi = value.MaSoGV;
					}
					else
					{
						this._MaSoGiamThi = default(string);
					}
					this.SendPropertyChanged("GiangVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhSachSinhVienThi")]
	public partial class DanhSachSinhVienThi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDS;
		
		private int _MaSoSV;
		
		private EntityRef<DanhSachThi> _DanhSachThi;
		
		private EntityRef<SinhVien> _SinhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDSChanging(string value);
    partial void OnMaDSChanged();
    partial void OnMaSoSVChanging(int value);
    partial void OnMaSoSVChanged();
    #endregion
		
		public DanhSachSinhVienThi()
		{
			this._DanhSachThi = default(EntityRef<DanhSachThi>);
			this._SinhVien = default(EntityRef<SinhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDS", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDS
		{
			get
			{
				return this._MaDS;
			}
			set
			{
				if ((this._MaDS != value))
				{
					if (this._DanhSachThi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDSChanging(value);
					this.SendPropertyChanging();
					this._MaDS = value;
					this.SendPropertyChanged("MaDS");
					this.OnMaDSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSoSV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaSoSV
		{
			get
			{
				return this._MaSoSV;
			}
			set
			{
				if ((this._MaSoSV != value))
				{
					if (this._SinhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSoSVChanging(value);
					this.SendPropertyChanging();
					this._MaSoSV = value;
					this.SendPropertyChanged("MaSoSV");
					this.OnMaSoSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DanhSachThi_DanhSachSinhVienThi", Storage="_DanhSachThi", ThisKey="MaDS", OtherKey="MaDS", IsForeignKey=true)]
		public DanhSachThi DanhSachThi
		{
			get
			{
				return this._DanhSachThi.Entity;
			}
			set
			{
				DanhSachThi previousValue = this._DanhSachThi.Entity;
				if (((previousValue != value) 
							|| (this._DanhSachThi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DanhSachThi.Entity = null;
						previousValue.DanhSachSinhVienThis.Remove(this);
					}
					this._DanhSachThi.Entity = value;
					if ((value != null))
					{
						value.DanhSachSinhVienThis.Add(this);
						this._MaDS = value.MaDS;
					}
					else
					{
						this._MaDS = default(string);
					}
					this.SendPropertyChanged("DanhSachThi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_DanhSachSinhVienThi", Storage="_SinhVien", ThisKey="MaSoSV", OtherKey="MaSoSV", IsForeignKey=true)]
		public SinhVien SinhVien
		{
			get
			{
				return this._SinhVien.Entity;
			}
			set
			{
				SinhVien previousValue = this._SinhVien.Entity;
				if (((previousValue != value) 
							|| (this._SinhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SinhVien.Entity = null;
						previousValue.DanhSachSinhVienThis.Remove(this);
					}
					this._SinhVien.Entity = value;
					if ((value != null))
					{
						value.DanhSachSinhVienThis.Add(this);
						this._MaSoSV = value.MaSoSV;
					}
					else
					{
						this._MaSoSV = default(int);
					}
					this.SendPropertyChanged("SinhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhSachThi")]
	public partial class DanhSachThi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDS;
		
		private string _MaSoHP;
		
		private string _MaPhongThi;
		
		private System.Nullable<System.DateTime> _NgayThi;
		
		private System.Nullable<System.TimeSpan> _GioBatDau;
		
		private System.Nullable<System.TimeSpan> _GioKetThuc;
		
		private EntitySet<DanhSachGiamThi> _DanhSachGiamThis;
		
		private EntitySet<DanhSachSinhVienThi> _DanhSachSinhVienThis;
		
		private EntityRef<PhongThi> _PhongThi;
		
		private EntityRef<HocPhan> _HocPhan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDSChanging(string value);
    partial void OnMaDSChanged();
    partial void OnMaSoHPChanging(string value);
    partial void OnMaSoHPChanged();
    partial void OnMaPhongThiChanging(string value);
    partial void OnMaPhongThiChanged();
    partial void OnNgayThiChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayThiChanged();
    partial void OnGioBatDauChanging(System.Nullable<System.TimeSpan> value);
    partial void OnGioBatDauChanged();
    partial void OnGioKetThucChanging(System.Nullable<System.TimeSpan> value);
    partial void OnGioKetThucChanged();
    #endregion
		
		public DanhSachThi()
		{
			this._DanhSachGiamThis = new EntitySet<DanhSachGiamThi>(new Action<DanhSachGiamThi>(this.attach_DanhSachGiamThis), new Action<DanhSachGiamThi>(this.detach_DanhSachGiamThis));
			this._DanhSachSinhVienThis = new EntitySet<DanhSachSinhVienThi>(new Action<DanhSachSinhVienThi>(this.attach_DanhSachSinhVienThis), new Action<DanhSachSinhVienThi>(this.detach_DanhSachSinhVienThis));
			this._PhongThi = default(EntityRef<PhongThi>);
			this._HocPhan = default(EntityRef<HocPhan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDS", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDS
		{
			get
			{
				return this._MaDS;
			}
			set
			{
				if ((this._MaDS != value))
				{
					this.OnMaDSChanging(value);
					this.SendPropertyChanging();
					this._MaDS = value;
					this.SendPropertyChanged("MaDS");
					this.OnMaDSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSoHP", DbType="VarChar(5)")]
		public string MaSoHP
		{
			get
			{
				return this._MaSoHP;
			}
			set
			{
				if ((this._MaSoHP != value))
				{
					if (this._HocPhan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSoHPChanging(value);
					this.SendPropertyChanging();
					this._MaSoHP = value;
					this.SendPropertyChanged("MaSoHP");
					this.OnMaSoHPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhongThi", DbType="VarChar(5)")]
		public string MaPhongThi
		{
			get
			{
				return this._MaPhongThi;
			}
			set
			{
				if ((this._MaPhongThi != value))
				{
					if (this._PhongThi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhongThiChanging(value);
					this.SendPropertyChanging();
					this._MaPhongThi = value;
					this.SendPropertyChanged("MaPhongThi");
					this.OnMaPhongThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThi", DbType="Date")]
		public System.Nullable<System.DateTime> NgayThi
		{
			get
			{
				return this._NgayThi;
			}
			set
			{
				if ((this._NgayThi != value))
				{
					this.OnNgayThiChanging(value);
					this.SendPropertyChanging();
					this._NgayThi = value;
					this.SendPropertyChanged("NgayThi");
					this.OnNgayThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioBatDau", DbType="Time")]
		public System.Nullable<System.TimeSpan> GioBatDau
		{
			get
			{
				return this._GioBatDau;
			}
			set
			{
				if ((this._GioBatDau != value))
				{
					this.OnGioBatDauChanging(value);
					this.SendPropertyChanging();
					this._GioBatDau = value;
					this.SendPropertyChanged("GioBatDau");
					this.OnGioBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioKetThuc", DbType="Time")]
		public System.Nullable<System.TimeSpan> GioKetThuc
		{
			get
			{
				return this._GioKetThuc;
			}
			set
			{
				if ((this._GioKetThuc != value))
				{
					this.OnGioKetThucChanging(value);
					this.SendPropertyChanging();
					this._GioKetThuc = value;
					this.SendPropertyChanged("GioKetThuc");
					this.OnGioKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DanhSachThi_DanhSachGiamThi", Storage="_DanhSachGiamThis", ThisKey="MaDS", OtherKey="MaDS")]
		public EntitySet<DanhSachGiamThi> DanhSachGiamThis
		{
			get
			{
				return this._DanhSachGiamThis;
			}
			set
			{
				this._DanhSachGiamThis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DanhSachThi_DanhSachSinhVienThi", Storage="_DanhSachSinhVienThis", ThisKey="MaDS", OtherKey="MaDS")]
		public EntitySet<DanhSachSinhVienThi> DanhSachSinhVienThis
		{
			get
			{
				return this._DanhSachSinhVienThis;
			}
			set
			{
				this._DanhSachSinhVienThis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongThi_DanhSachThi", Storage="_PhongThi", ThisKey="MaPhongThi", OtherKey="MaPhongThi", IsForeignKey=true)]
		public PhongThi PhongThi
		{
			get
			{
				return this._PhongThi.Entity;
			}
			set
			{
				PhongThi previousValue = this._PhongThi.Entity;
				if (((previousValue != value) 
							|| (this._PhongThi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhongThi.Entity = null;
						previousValue.DanhSachThis.Remove(this);
					}
					this._PhongThi.Entity = value;
					if ((value != null))
					{
						value.DanhSachThis.Add(this);
						this._MaPhongThi = value.MaPhongThi;
					}
					else
					{
						this._MaPhongThi = default(string);
					}
					this.SendPropertyChanged("PhongThi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocPhan_DanhSachThi", Storage="_HocPhan", ThisKey="MaSoHP", OtherKey="MaSoHP", IsForeignKey=true)]
		public HocPhan HocPhan
		{
			get
			{
				return this._HocPhan.Entity;
			}
			set
			{
				HocPhan previousValue = this._HocPhan.Entity;
				if (((previousValue != value) 
							|| (this._HocPhan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HocPhan.Entity = null;
						previousValue.DanhSachThis.Remove(this);
					}
					this._HocPhan.Entity = value;
					if ((value != null))
					{
						value.DanhSachThis.Add(this);
						this._MaSoHP = value.MaSoHP;
					}
					else
					{
						this._MaSoHP = default(string);
					}
					this.SendPropertyChanged("HocPhan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DanhSachGiamThis(DanhSachGiamThi entity)
		{
			this.SendPropertyChanging();
			entity.DanhSachThi = this;
		}
		
		private void detach_DanhSachGiamThis(DanhSachGiamThi entity)
		{
			this.SendPropertyChanging();
			entity.DanhSachThi = null;
		}
		
		private void attach_DanhSachSinhVienThis(DanhSachSinhVienThi entity)
		{
			this.SendPropertyChanging();
			entity.DanhSachThi = this;
		}
		
		private void detach_DanhSachSinhVienThis(DanhSachSinhVienThi entity)
		{
			this.SendPropertyChanging();
			entity.DanhSachThi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DeThi")]
	public partial class DeThi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDeThi;
		
		private string _MaSoHP;
		
		private System.Nullable<int> _ThoiGian;
		
		private System.Nullable<int> _SoCauRatDe;
		
		private System.Nullable<int> _SoCauDe;
		
		private System.Nullable<int> _SoCauTB;
		
		private System.Nullable<int> _SoCauKho;
		
		private System.Nullable<int> _SoCauRatKho;
		
		private string _DotThi;
		
		private EntitySet<ChiTietDeThi> _ChiTietDeThis;
		
		private EntitySet<KetQuaThi> _KetQuaThis;
		
		private EntityRef<HocPhan> _HocPhan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDeThiChanging(int value);
    partial void OnMaDeThiChanged();
    partial void OnMaSoHPChanging(string value);
    partial void OnMaSoHPChanged();
    partial void OnThoiGianChanging(System.Nullable<int> value);
    partial void OnThoiGianChanged();
    partial void OnSoCauRatDeChanging(System.Nullable<int> value);
    partial void OnSoCauRatDeChanged();
    partial void OnSoCauDeChanging(System.Nullable<int> value);
    partial void OnSoCauDeChanged();
    partial void OnSoCauTBChanging(System.Nullable<int> value);
    partial void OnSoCauTBChanged();
    partial void OnSoCauKhoChanging(System.Nullable<int> value);
    partial void OnSoCauKhoChanged();
    partial void OnSoCauRatKhoChanging(System.Nullable<int> value);
    partial void OnSoCauRatKhoChanged();
    partial void OnDotThiChanging(string value);
    partial void OnDotThiChanged();
    #endregion
		
		public DeThi()
		{
			this._ChiTietDeThis = new EntitySet<ChiTietDeThi>(new Action<ChiTietDeThi>(this.attach_ChiTietDeThis), new Action<ChiTietDeThi>(this.detach_ChiTietDeThis));
			this._KetQuaThis = new EntitySet<KetQuaThi>(new Action<KetQuaThi>(this.attach_KetQuaThis), new Action<KetQuaThi>(this.detach_KetQuaThis));
			this._HocPhan = default(EntityRef<HocPhan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDeThi", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDeThi
		{
			get
			{
				return this._MaDeThi;
			}
			set
			{
				if ((this._MaDeThi != value))
				{
					this.OnMaDeThiChanging(value);
					this.SendPropertyChanging();
					this._MaDeThi = value;
					this.SendPropertyChanged("MaDeThi");
					this.OnMaDeThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSoHP", DbType="VarChar(5)")]
		public string MaSoHP
		{
			get
			{
				return this._MaSoHP;
			}
			set
			{
				if ((this._MaSoHP != value))
				{
					if (this._HocPhan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSoHPChanging(value);
					this.SendPropertyChanging();
					this._MaSoHP = value;
					this.SendPropertyChanged("MaSoHP");
					this.OnMaSoHPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGian", DbType="Int")]
		public System.Nullable<int> ThoiGian
		{
			get
			{
				return this._ThoiGian;
			}
			set
			{
				if ((this._ThoiGian != value))
				{
					this.OnThoiGianChanging(value);
					this.SendPropertyChanging();
					this._ThoiGian = value;
					this.SendPropertyChanged("ThoiGian");
					this.OnThoiGianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCauRatDe", DbType="Int")]
		public System.Nullable<int> SoCauRatDe
		{
			get
			{
				return this._SoCauRatDe;
			}
			set
			{
				if ((this._SoCauRatDe != value))
				{
					this.OnSoCauRatDeChanging(value);
					this.SendPropertyChanging();
					this._SoCauRatDe = value;
					this.SendPropertyChanged("SoCauRatDe");
					this.OnSoCauRatDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCauDe", DbType="Int")]
		public System.Nullable<int> SoCauDe
		{
			get
			{
				return this._SoCauDe;
			}
			set
			{
				if ((this._SoCauDe != value))
				{
					this.OnSoCauDeChanging(value);
					this.SendPropertyChanging();
					this._SoCauDe = value;
					this.SendPropertyChanged("SoCauDe");
					this.OnSoCauDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCauTB", DbType="Int")]
		public System.Nullable<int> SoCauTB
		{
			get
			{
				return this._SoCauTB;
			}
			set
			{
				if ((this._SoCauTB != value))
				{
					this.OnSoCauTBChanging(value);
					this.SendPropertyChanging();
					this._SoCauTB = value;
					this.SendPropertyChanged("SoCauTB");
					this.OnSoCauTBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCauKho", DbType="Int")]
		public System.Nullable<int> SoCauKho
		{
			get
			{
				return this._SoCauKho;
			}
			set
			{
				if ((this._SoCauKho != value))
				{
					this.OnSoCauKhoChanging(value);
					this.SendPropertyChanging();
					this._SoCauKho = value;
					this.SendPropertyChanged("SoCauKho");
					this.OnSoCauKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCauRatKho", DbType="Int")]
		public System.Nullable<int> SoCauRatKho
		{
			get
			{
				return this._SoCauRatKho;
			}
			set
			{
				if ((this._SoCauRatKho != value))
				{
					this.OnSoCauRatKhoChanging(value);
					this.SendPropertyChanging();
					this._SoCauRatKho = value;
					this.SendPropertyChanged("SoCauRatKho");
					this.OnSoCauRatKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DotThi", DbType="VarChar(30)")]
		public string DotThi
		{
			get
			{
				return this._DotThi;
			}
			set
			{
				if ((this._DotThi != value))
				{
					this.OnDotThiChanging(value);
					this.SendPropertyChanging();
					this._DotThi = value;
					this.SendPropertyChanged("DotThi");
					this.OnDotThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DeThi_ChiTietDeThi", Storage="_ChiTietDeThis", ThisKey="MaDeThi", OtherKey="MaDeThi")]
		public EntitySet<ChiTietDeThi> ChiTietDeThis
		{
			get
			{
				return this._ChiTietDeThis;
			}
			set
			{
				this._ChiTietDeThis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DeThi_KetQuaThi", Storage="_KetQuaThis", ThisKey="MaDeThi", OtherKey="MaDeThi")]
		public EntitySet<KetQuaThi> KetQuaThis
		{
			get
			{
				return this._KetQuaThis;
			}
			set
			{
				this._KetQuaThis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocPhan_DeThi", Storage="_HocPhan", ThisKey="MaSoHP", OtherKey="MaSoHP", IsForeignKey=true)]
		public HocPhan HocPhan
		{
			get
			{
				return this._HocPhan.Entity;
			}
			set
			{
				HocPhan previousValue = this._HocPhan.Entity;
				if (((previousValue != value) 
							|| (this._HocPhan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HocPhan.Entity = null;
						previousValue.DeThis.Remove(this);
					}
					this._HocPhan.Entity = value;
					if ((value != null))
					{
						value.DeThis.Add(this);
						this._MaSoHP = value.MaSoHP;
					}
					else
					{
						this._MaSoHP = default(string);
					}
					this.SendPropertyChanged("HocPhan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietDeThis(ChiTietDeThi entity)
		{
			this.SendPropertyChanging();
			entity.DeThi = this;
		}
		
		private void detach_ChiTietDeThis(ChiTietDeThi entity)
		{
			this.SendPropertyChanging();
			entity.DeThi = null;
		}
		
		private void attach_KetQuaThis(KetQuaThi entity)
		{
			this.SendPropertyChanging();
			entity.DeThi = this;
		}
		
		private void detach_KetQuaThis(KetQuaThi entity)
		{
			this.SendPropertyChanging();
			entity.DeThi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GiangVien")]
	public partial class GiangVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSoGV;
		
		private string _HoTen;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _HocVi;
		
		private string _MaKhoa;
		
		private EntitySet<CauHoi> _CauHois;
		
		private EntitySet<DanhSachGiamThi> _DanhSachGiamThis;
		
		private EntityRef<Khoa> _Khoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSoGVChanging(string value);
    partial void OnMaSoGVChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnHocViChanging(string value);
    partial void OnHocViChanged();
    partial void OnMaKhoaChanging(string value);
    partial void OnMaKhoaChanged();
    #endregion
		
		public GiangVien()
		{
			this._CauHois = new EntitySet<CauHoi>(new Action<CauHoi>(this.attach_CauHois), new Action<CauHoi>(this.detach_CauHois));
			this._DanhSachGiamThis = new EntitySet<DanhSachGiamThi>(new Action<DanhSachGiamThi>(this.attach_DanhSachGiamThis), new Action<DanhSachGiamThi>(this.detach_DanhSachGiamThis));
			this._Khoa = default(EntityRef<Khoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSoGV", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSoGV
		{
			get
			{
				return this._MaSoGV;
			}
			set
			{
				if ((this._MaSoGV != value))
				{
					this.OnMaSoGVChanging(value);
					this.SendPropertyChanging();
					this._MaSoGV = value;
					this.SendPropertyChanged("MaSoGV");
					this.OnMaSoGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(60)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HocVi", DbType="NVarChar(40)")]
		public string HocVi
		{
			get
			{
				return this._HocVi;
			}
			set
			{
				if ((this._HocVi != value))
				{
					this.OnHocViChanging(value);
					this.SendPropertyChanging();
					this._HocVi = value;
					this.SendPropertyChanged("HocVi");
					this.OnHocViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoa", DbType="VarChar(5)")]
		public string MaKhoa
		{
			get
			{
				return this._MaKhoa;
			}
			set
			{
				if ((this._MaKhoa != value))
				{
					if (this._Khoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhoaChanging(value);
					this.SendPropertyChanging();
					this._MaKhoa = value;
					this.SendPropertyChanged("MaKhoa");
					this.OnMaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_CauHoi", Storage="_CauHois", ThisKey="MaSoGV", OtherKey="GiangVienSoan")]
		public EntitySet<CauHoi> CauHois
		{
			get
			{
				return this._CauHois;
			}
			set
			{
				this._CauHois.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_DanhSachGiamThi", Storage="_DanhSachGiamThis", ThisKey="MaSoGV", OtherKey="MaSoGiamThi")]
		public EntitySet<DanhSachGiamThi> DanhSachGiamThis
		{
			get
			{
				return this._DanhSachGiamThis;
			}
			set
			{
				this._DanhSachGiamThis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_GiangVien", Storage="_Khoa", ThisKey="MaKhoa", OtherKey="MaKhoa", IsForeignKey=true)]
		public Khoa Khoa
		{
			get
			{
				return this._Khoa.Entity;
			}
			set
			{
				Khoa previousValue = this._Khoa.Entity;
				if (((previousValue != value) 
							|| (this._Khoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khoa.Entity = null;
						previousValue.GiangViens.Remove(this);
					}
					this._Khoa.Entity = value;
					if ((value != null))
					{
						value.GiangViens.Add(this);
						this._MaKhoa = value.MaKhoa;
					}
					else
					{
						this._MaKhoa = default(string);
					}
					this.SendPropertyChanged("Khoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CauHois(CauHoi entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien = this;
		}
		
		private void detach_CauHois(CauHoi entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien = null;
		}
		
		private void attach_DanhSachGiamThis(DanhSachGiamThi entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien = this;
		}
		
		private void detach_DanhSachGiamThis(DanhSachGiamThi entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HocPhan")]
	public partial class HocPhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSoHP;
		
		private string _TenHP;
		
		private System.Nullable<int> _SoTinChi;
		
		private EntitySet<CauHoi> _CauHois;
		
		private EntitySet<DanhSachThi> _DanhSachThis;
		
		private EntitySet<DeThi> _DeThis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSoHPChanging(string value);
    partial void OnMaSoHPChanged();
    partial void OnTenHPChanging(string value);
    partial void OnTenHPChanged();
    partial void OnSoTinChiChanging(System.Nullable<int> value);
    partial void OnSoTinChiChanged();
    #endregion
		
		public HocPhan()
		{
			this._CauHois = new EntitySet<CauHoi>(new Action<CauHoi>(this.attach_CauHois), new Action<CauHoi>(this.detach_CauHois));
			this._DanhSachThis = new EntitySet<DanhSachThi>(new Action<DanhSachThi>(this.attach_DanhSachThis), new Action<DanhSachThi>(this.detach_DanhSachThis));
			this._DeThis = new EntitySet<DeThi>(new Action<DeThi>(this.attach_DeThis), new Action<DeThi>(this.detach_DeThis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSoHP", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSoHP
		{
			get
			{
				return this._MaSoHP;
			}
			set
			{
				if ((this._MaSoHP != value))
				{
					this.OnMaSoHPChanging(value);
					this.SendPropertyChanging();
					this._MaSoHP = value;
					this.SendPropertyChanged("MaSoHP");
					this.OnMaSoHPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHP", DbType="NVarChar(40)")]
		public string TenHP
		{
			get
			{
				return this._TenHP;
			}
			set
			{
				if ((this._TenHP != value))
				{
					this.OnTenHPChanging(value);
					this.SendPropertyChanging();
					this._TenHP = value;
					this.SendPropertyChanged("TenHP");
					this.OnTenHPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTinChi", DbType="Int")]
		public System.Nullable<int> SoTinChi
		{
			get
			{
				return this._SoTinChi;
			}
			set
			{
				if ((this._SoTinChi != value))
				{
					this.OnSoTinChiChanging(value);
					this.SendPropertyChanging();
					this._SoTinChi = value;
					this.SendPropertyChanged("SoTinChi");
					this.OnSoTinChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocPhan_CauHoi", Storage="_CauHois", ThisKey="MaSoHP", OtherKey="MaSoHP")]
		public EntitySet<CauHoi> CauHois
		{
			get
			{
				return this._CauHois;
			}
			set
			{
				this._CauHois.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocPhan_DanhSachThi", Storage="_DanhSachThis", ThisKey="MaSoHP", OtherKey="MaSoHP")]
		public EntitySet<DanhSachThi> DanhSachThis
		{
			get
			{
				return this._DanhSachThis;
			}
			set
			{
				this._DanhSachThis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocPhan_DeThi", Storage="_DeThis", ThisKey="MaSoHP", OtherKey="MaSoHP")]
		public EntitySet<DeThi> DeThis
		{
			get
			{
				return this._DeThis;
			}
			set
			{
				this._DeThis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CauHois(CauHoi entity)
		{
			this.SendPropertyChanging();
			entity.HocPhan = this;
		}
		
		private void detach_CauHois(CauHoi entity)
		{
			this.SendPropertyChanging();
			entity.HocPhan = null;
		}
		
		private void attach_DanhSachThis(DanhSachThi entity)
		{
			this.SendPropertyChanging();
			entity.HocPhan = this;
		}
		
		private void detach_DanhSachThis(DanhSachThi entity)
		{
			this.SendPropertyChanging();
			entity.HocPhan = null;
		}
		
		private void attach_DeThis(DeThi entity)
		{
			this.SendPropertyChanging();
			entity.HocPhan = this;
		}
		
		private void detach_DeThis(DeThi entity)
		{
			this.SendPropertyChanging();
			entity.HocPhan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KetQuaThi")]
	public partial class KetQuaThi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaSoKQ;
		
		private int _MaSoSV;
		
		private int _MaDeThi;
		
		private System.Nullable<double> _Diem;
		
		private EntityRef<DeThi> _DeThi;
		
		private EntityRef<SinhVien> _SinhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSoKQChanging(int value);
    partial void OnMaSoKQChanged();
    partial void OnMaSoSVChanging(int value);
    partial void OnMaSoSVChanged();
    partial void OnMaDeThiChanging(int value);
    partial void OnMaDeThiChanged();
    partial void OnDiemChanging(System.Nullable<double> value);
    partial void OnDiemChanged();
    #endregion
		
		public KetQuaThi()
		{
			this._DeThi = default(EntityRef<DeThi>);
			this._SinhVien = default(EntityRef<SinhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSoKQ", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaSoKQ
		{
			get
			{
				return this._MaSoKQ;
			}
			set
			{
				if ((this._MaSoKQ != value))
				{
					this.OnMaSoKQChanging(value);
					this.SendPropertyChanging();
					this._MaSoKQ = value;
					this.SendPropertyChanged("MaSoKQ");
					this.OnMaSoKQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSoSV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaSoSV
		{
			get
			{
				return this._MaSoSV;
			}
			set
			{
				if ((this._MaSoSV != value))
				{
					if (this._SinhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSoSVChanging(value);
					this.SendPropertyChanging();
					this._MaSoSV = value;
					this.SendPropertyChanged("MaSoSV");
					this.OnMaSoSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDeThi", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaDeThi
		{
			get
			{
				return this._MaDeThi;
			}
			set
			{
				if ((this._MaDeThi != value))
				{
					if (this._DeThi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDeThiChanging(value);
					this.SendPropertyChanging();
					this._MaDeThi = value;
					this.SendPropertyChanged("MaDeThi");
					this.OnMaDeThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diem", DbType="Float")]
		public System.Nullable<double> Diem
		{
			get
			{
				return this._Diem;
			}
			set
			{
				if ((this._Diem != value))
				{
					this.OnDiemChanging(value);
					this.SendPropertyChanging();
					this._Diem = value;
					this.SendPropertyChanged("Diem");
					this.OnDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DeThi_KetQuaThi", Storage="_DeThi", ThisKey="MaDeThi", OtherKey="MaDeThi", IsForeignKey=true)]
		public DeThi DeThi
		{
			get
			{
				return this._DeThi.Entity;
			}
			set
			{
				DeThi previousValue = this._DeThi.Entity;
				if (((previousValue != value) 
							|| (this._DeThi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DeThi.Entity = null;
						previousValue.KetQuaThis.Remove(this);
					}
					this._DeThi.Entity = value;
					if ((value != null))
					{
						value.KetQuaThis.Add(this);
						this._MaDeThi = value.MaDeThi;
					}
					else
					{
						this._MaDeThi = default(int);
					}
					this.SendPropertyChanged("DeThi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_KetQuaThi", Storage="_SinhVien", ThisKey="MaSoSV", OtherKey="MaSoSV", IsForeignKey=true)]
		public SinhVien SinhVien
		{
			get
			{
				return this._SinhVien.Entity;
			}
			set
			{
				SinhVien previousValue = this._SinhVien.Entity;
				if (((previousValue != value) 
							|| (this._SinhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SinhVien.Entity = null;
						previousValue.KetQuaThis.Remove(this);
					}
					this._SinhVien.Entity = value;
					if ((value != null))
					{
						value.KetQuaThis.Add(this);
						this._MaSoSV = value.MaSoSV;
					}
					else
					{
						this._MaSoSV = default(int);
					}
					this.SendPropertyChanged("SinhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Khoa")]
	public partial class Khoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhoa;
		
		private string _TenKhoa;
		
		private EntitySet<GiangVien> _GiangViens;
		
		private EntitySet<SinhVien> _SinhViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhoaChanging(string value);
    partial void OnMaKhoaChanged();
    partial void OnTenKhoaChanging(string value);
    partial void OnTenKhoaChanged();
    #endregion
		
		public Khoa()
		{
			this._GiangViens = new EntitySet<GiangVien>(new Action<GiangVien>(this.attach_GiangViens), new Action<GiangVien>(this.detach_GiangViens));
			this._SinhViens = new EntitySet<SinhVien>(new Action<SinhVien>(this.attach_SinhViens), new Action<SinhVien>(this.detach_SinhViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoa", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhoa
		{
			get
			{
				return this._MaKhoa;
			}
			set
			{
				if ((this._MaKhoa != value))
				{
					this.OnMaKhoaChanging(value);
					this.SendPropertyChanging();
					this._MaKhoa = value;
					this.SendPropertyChanged("MaKhoa");
					this.OnMaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhoa", DbType="NVarChar(40)")]
		public string TenKhoa
		{
			get
			{
				return this._TenKhoa;
			}
			set
			{
				if ((this._TenKhoa != value))
				{
					this.OnTenKhoaChanging(value);
					this.SendPropertyChanging();
					this._TenKhoa = value;
					this.SendPropertyChanged("TenKhoa");
					this.OnTenKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_GiangVien", Storage="_GiangViens", ThisKey="MaKhoa", OtherKey="MaKhoa")]
		public EntitySet<GiangVien> GiangViens
		{
			get
			{
				return this._GiangViens;
			}
			set
			{
				this._GiangViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_SinhVien", Storage="_SinhViens", ThisKey="MaKhoa", OtherKey="MaKhoa")]
		public EntitySet<SinhVien> SinhViens
		{
			get
			{
				return this._SinhViens;
			}
			set
			{
				this._SinhViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GiangViens(GiangVien entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = this;
		}
		
		private void detach_GiangViens(GiangVien entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = null;
		}
		
		private void attach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = this;
		}
		
		private void detach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SinhVien")]
	public partial class SinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaSoSV;
		
		private string _HoTen;
		
		private string _NgaySinh;
		
		private string _MaKhoa;
		
		private EntitySet<DanhSachSinhVienThi> _DanhSachSinhVienThis;
		
		private EntitySet<KetQuaThi> _KetQuaThis;
		
		private EntityRef<Khoa> _Khoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSoSVChanging(int value);
    partial void OnMaSoSVChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgaySinhChanging(string value);
    partial void OnNgaySinhChanged();
    partial void OnMaKhoaChanging(string value);
    partial void OnMaKhoaChanged();
    #endregion
		
		public SinhVien()
		{
			this._DanhSachSinhVienThis = new EntitySet<DanhSachSinhVienThi>(new Action<DanhSachSinhVienThi>(this.attach_DanhSachSinhVienThis), new Action<DanhSachSinhVienThi>(this.detach_DanhSachSinhVienThis));
			this._KetQuaThis = new EntitySet<KetQuaThi>(new Action<KetQuaThi>(this.attach_KetQuaThis), new Action<KetQuaThi>(this.detach_KetQuaThis));
			this._Khoa = default(EntityRef<Khoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSoSV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaSoSV
		{
			get
			{
				return this._MaSoSV;
			}
			set
			{
				if ((this._MaSoSV != value))
				{
					this.OnMaSoSVChanging(value);
					this.SendPropertyChanging();
					this._MaSoSV = value;
					this.SendPropertyChanged("MaSoSV");
					this.OnMaSoSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(60)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="VarChar(11)")]
		public string NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoa", DbType="VarChar(5)")]
		public string MaKhoa
		{
			get
			{
				return this._MaKhoa;
			}
			set
			{
				if ((this._MaKhoa != value))
				{
					if (this._Khoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhoaChanging(value);
					this.SendPropertyChanging();
					this._MaKhoa = value;
					this.SendPropertyChanged("MaKhoa");
					this.OnMaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_DanhSachSinhVienThi", Storage="_DanhSachSinhVienThis", ThisKey="MaSoSV", OtherKey="MaSoSV")]
		public EntitySet<DanhSachSinhVienThi> DanhSachSinhVienThis
		{
			get
			{
				return this._DanhSachSinhVienThis;
			}
			set
			{
				this._DanhSachSinhVienThis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_KetQuaThi", Storage="_KetQuaThis", ThisKey="MaSoSV", OtherKey="MaSoSV")]
		public EntitySet<KetQuaThi> KetQuaThis
		{
			get
			{
				return this._KetQuaThis;
			}
			set
			{
				this._KetQuaThis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_SinhVien", Storage="_Khoa", ThisKey="MaKhoa", OtherKey="MaKhoa", IsForeignKey=true)]
		public Khoa Khoa
		{
			get
			{
				return this._Khoa.Entity;
			}
			set
			{
				Khoa previousValue = this._Khoa.Entity;
				if (((previousValue != value) 
							|| (this._Khoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khoa.Entity = null;
						previousValue.SinhViens.Remove(this);
					}
					this._Khoa.Entity = value;
					if ((value != null))
					{
						value.SinhViens.Add(this);
						this._MaKhoa = value.MaKhoa;
					}
					else
					{
						this._MaKhoa = default(string);
					}
					this.SendPropertyChanged("Khoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DanhSachSinhVienThis(DanhSachSinhVienThi entity)
		{
			this.SendPropertyChanging();
			entity.SinhVien = this;
		}
		
		private void detach_DanhSachSinhVienThis(DanhSachSinhVienThi entity)
		{
			this.SendPropertyChanging();
			entity.SinhVien = null;
		}
		
		private void attach_KetQuaThis(KetQuaThi entity)
		{
			this.SendPropertyChanging();
			entity.SinhVien = this;
		}
		
		private void detach_KetQuaThis(KetQuaThi entity)
		{
			this.SendPropertyChanging();
			entity.SinhVien = null;
		}
	}
}
#pragma warning restore 1591
